monsieurbiz_sylius_homepage_admin:
    resource: |
        alias: monsieurbiz_homepage.homepage
        section: admin
        permission: true
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: monsieurbiz_homepage
    type: sylius.resource
