services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Sylius\Bundle\ResourceBundle\Controller\ResourceController:
            autowire: false

    MonsieurBiz\SyliusHomepagePlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'
        
    MonsieurBiz\SyliusHomepagePlugin\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Menu item in admin panel
    MonsieurBiz\SyliusHomepagePlugin\Menu\AdminMenuListener:
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItem }

    # Homepage Forms
    MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageType:
        arguments:
            $dataClass: '%monsieurbiz_homepage.model.homepage.class%'
            $validationGroups: ['monsieurbiz']

    MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageTranslationType:
        arguments:
            $dataClass: '%monsieurbiz_homepage.model.homepage_translation.class%'
            $validationGroups: ['monsieurbiz']

    # Live components
    sylius_admin.monsieurbiz_homepage.twig.component.homepage.form:
        autoconfigure: false
        class: Sylius\Bundle\UiBundle\Twig\Component\ResourceFormComponent
        arguments:
            - '@monsieurbiz_homepage.repository.homepage'
            - '@form.factory'
            - '%monsieurbiz_homepage.model.homepage.class%'
            - 'MonsieurBiz\SyliusHomepagePlugin\Form\Type\HomepageType'
        tags:
            - { name: 'sylius.live_component.admin', key: 'sylius_admin:monsieurbiz_homepage:homepage:form' }
